
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class ChatBox
{

    public int ID { get; set; }

    public Nullable<int> ComplaintID { get; set; }

    public string Remarks { get; set; }

    public Nullable<int> SOID { get; set; }

    public Nullable<System.DateTime> DateInstall { get; set; }



    public virtual Job Job { get; set; }

}

}
