
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class ComplaintStatu
{

    public int Id { get; set; }

    public string Name { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string Color { get; set; }

}

}
