
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class EquipmentCategory
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EquipmentCategory()
    {

        this.EquipmentTypes = new HashSet<EquipmentType>();

        this.SiteEquipmentDetails = new HashSet<SiteEquipmentDetail>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<bool> isdeleted { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EquipmentType> EquipmentTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SiteEquipmentDetail> SiteEquipmentDetails { get; set; }

}

}
