
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Item
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Item()
    {

        this.JobItems = new HashSet<JobItem>();

        this.tbl_StockDetail = new HashSet<tbl_StockDetail>();

    }


    public int ItemID { get; set; }

    public string ItemName { get; set; }

    public string ItemDesc { get; set; }

    public string ItemCode { get; set; }

    public decimal Price { get; set; }

    public int MainCategID { get; set; }

    public int SubCategID { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<int> SubCategIDA { get; set; }

    public int Packing { get; set; }

    public Nullable<int> SortOrder { get; set; }



    public virtual MainCategory MainCategory { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<JobItem> JobItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_StockDetail> tbl_StockDetail { get; set; }

}

}
