
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class JobItem
{

    public long JobItemID { get; set; }

    public int JobID { get; set; }

    public int ItemID { get; set; }

    public decimal Quantity { get; set; }

    public Nullable<decimal> Price { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public string DispatchQuantity { get; set; }

    public Nullable<System.DateTime> DispatchDate { get; set; }

    public string Status { get; set; }



    public virtual Job Job { get; set; }

    public virtual Item Item { get; set; }

}

}
