
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class NotificationSeen
{

    public int ID { get; set; }

    public Nullable<int> JobID { get; set; }

    public Nullable<int> JobDetailID { get; set; }

    public Nullable<int> ComplainthistoryID { get; set; }

    public Nullable<int> ComplaintNotificationID { get; set; }

    public Nullable<int> SOID { get; set; }

    public Nullable<bool> IsSeen { get; set; }



    public virtual ComplaintNotification ComplaintNotification { get; set; }

    public virtual Job Job { get; set; }

    public virtual JobsDetail JobsDetail { get; set; }

    public virtual Tbl_ComplaintHistory Tbl_ComplaintHistory { get; set; }

}

}
