
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class OneSignalUser
{

    public int ID { get; set; }

    public string OneSidnalUserID { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> HeadID { get; set; }

    public Nullable<int> RoleID { get; set; }



    public virtual SaleOfficer SaleOfficer { get; set; }

}

}
