
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Region
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Region()
    {

        this.Cities = new HashSet<City>();

        this.RegionalHeadRegions = new HashSet<RegionalHeadRegion>();

        this.Dealers = new HashSet<Dealer>();

        this.Tbl_Access = new HashSet<Tbl_Access>();

    }


    public int TID { get; set; }

    public int ID { get; set; }

    public string Name { get; set; }

    public string ShortCode { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public System.DateTime LastUpdate { get; set; }

    public string Location { get; set; }

    public string KSBRef { get; set; }

    public string ContactNo { get; set; }

    public string Province { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string Address { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<City> Cities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RegionalHeadRegion> RegionalHeadRegions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dealer> Dealers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tbl_Access> Tbl_Access { get; set; }

}

}
