
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class SiteEquipmentDetail
{

    public int ID { get; set; }

    public Nullable<int> SiteID { get; set; }

    public Nullable<int> EquipmentCategoryID { get; set; }

    public Nullable<int> EquipmentTypeID { get; set; }

    public string MaterialNo { get; set; }

    public Nullable<int> BrandID { get; set; }

    public string Condition { get; set; }

    public string Capacity { get; set; }

    public string Size { get; set; }

    public string Color { get; set; }

    public string YearOfManufacture { get; set; }

    public string YearOfInstall { get; set; }

    public Nullable<bool> Guarantee { get; set; }

    public string GuaranteeDetail { get; set; }

    public Nullable<System.DateTime> ExpiryDate { get; set; }

    public Nullable<bool> MaintainedBy { get; set; }

    public string MaintainedByWhome { get; set; }

    public string Weight { get; set; }

    public string MediumInUse { get; set; }

    public string OperatingTemperature { get; set; }

    public string OperatingPressure { get; set; }

    public string Remarks { get; set; }



    public virtual EquipmentBrand EquipmentBrand { get; set; }

    public virtual EquipmentCategory EquipmentCategory { get; set; }

    public virtual EquipmentType EquipmentType { get; set; }

    public virtual Retailer Retailer { get; set; }

}

}
