
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    
public partial class Sp_GetProgressView1_1_Result1
{

    public string Picture1 { get; set; }

    public string Picture2 { get; set; }

    public string Picture3 { get; set; }

    public Nullable<System.DateTime> JobDate { get; set; }

    public Nullable<int> ProgressStatusID { get; set; }

    public string ProgressStatusName { get; set; }

    public string ProgressStatusOtherRemarks { get; set; }

    public string FaulttypeDetailOtherRemarks { get; set; }

    public string PRemarks { get; set; }

    public string SaleofficerName { get; set; }

    public Nullable<int> FaultTypeId { get; set; }

    public Nullable<int> FaultTypeDetailID { get; set; }

    public Nullable<int> ComplaintStatusID { get; set; }

}

}
