
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    
public partial class Sp_KSBChildNotificationsforCC_Result2
{

    public Nullable<int> ComplaintID { get; set; }

    public string SiteName { get; set; }

    public Nullable<bool> IsSiteIDChanged { get; set; }

    public string SiteCode { get; set; }

    public Nullable<bool> IsSiteCodeChanged { get; set; }

    public string FaultType { get; set; }

    public Nullable<bool> IsFaulttypeIDChanged { get; set; }

    public string FaultTypeDetail { get; set; }

    public Nullable<bool> isFaultTypeDetailIDChanged { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string ComplaintStatusName { get; set; }

    public Nullable<bool> IsComplaintStatusIDChanged { get; set; }

    public string PersonName { get; set; }

    public Nullable<bool> IsPersonNameChanged { get; set; }

    public string Picture1 { get; set; }

    public Nullable<bool> IsPicture1Changed { get; set; }

    public string Picture2 { get; set; }

    public Nullable<bool> IsPicture2Changed { get; set; }

    public string Picture3 { get; set; }

    public Nullable<bool> IsPicture3Changed { get; set; }

    public string ProgressStatusName { get; set; }

    public Nullable<bool> IsProgressStatusIDChanged { get; set; }

    public string FaultTypeDetailRemarks { get; set; }

    public Nullable<bool> IsFaultTypeDetailRemarksChanged { get; set; }

    public string ProgressStatusRemarks { get; set; }

    public Nullable<bool> IsProgressStatusRemarksChanged { get; set; }

    public string AssignedSaleOfficerName { get; set; }

    public Nullable<bool> IsAssignedSaleOfficerChanged { get; set; }

    public string UpdateRemarks { get; set; }

    public Nullable<bool> IsUpdateRemarksChanged { get; set; }

}

}
