
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    
public partial class Sp_MyComplaintListRemarks1_2_Result1
{

    public int ComplaintID { get; set; }

    public string ProgressRemarks { get; set; }

    public Nullable<int> SaleOfficerID { get; set; }

    public string SaleOfficerName { get; set; }

    public string ProgressStatusName { get; set; }

    public string ProgressStatusRemarks { get; set; }

    public Nullable<int> ProgressstatusId { get; set; }

}

}
