
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class SubDivision
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SubDivision()
    {

        this.TBL_RouteSelection = new HashSet<TBL_RouteSelection>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public Nullable<int> CityID { get; set; }

    public Nullable<int> AreaID { get; set; }

    public string Code { get; set; }

    public Nullable<int> AreaIDRef { get; set; }

    public Nullable<int> AreaSrno { get; set; }

    public string DisplayFieldinArea { get; set; }



    public virtual Area Area { get; set; }

    public virtual City City { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TBL_RouteSelection> TBL_RouteSelection { get; set; }

}

}
