
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_MeterredingMultiValues
{

    public int ID { get; set; }

    public Nullable<int> ConsumerID { get; set; }

    public Nullable<int> MultiselectID { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<int> JobID { get; set; }

    public Nullable<decimal> Latitude { get; set; }

    public Nullable<decimal> Longitude { get; set; }

}

}
