
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_RouteSelection
{

    public int ID { get; set; }

    public Nullable<int> SOID { get; set; }

    public Nullable<System.DateTime> Createddate { get; set; }

    public Nullable<int> DDRID { get; set; }

    public Nullable<int> WardID { get; set; }

    public Nullable<int> AreaID { get; set; }

    public Nullable<bool> IsActive { get; set; }



    public virtual Area Area { get; set; }

    public virtual City City { get; set; }

    public virtual SaleOfficer SaleOfficer { get; set; }

    public virtual SubDivision SubDivision { get; set; }

}

}
