
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_Consumers
{

    public int ID { get; set; }

    public Nullable<int> DDRID { get; set; }

    public Nullable<int> WardID { get; set; }

    public Nullable<int> AreaID { get; set; }

    public Nullable<int> ConsumerID { get; set; }

    public string ConsumerName { get; set; }

    public string F_Name { get; set; }

    public Nullable<int> CNIC { get; set; }

    public string Address { get; set; }

    public Nullable<int> AreaMarla { get; set; }

    public Nullable<int> ConnectionCode { get; set; }

    public Nullable<int> WalkSortNo { get; set; }

    public Nullable<int> MeterNo { get; set; }

    public Nullable<int> DigitCode { get; set; }

    public Nullable<int> AreaSerial { get; set; }

    public Nullable<int> StatusID { get; set; }

    public Nullable<decimal> Latitude { get; set; }

    public Nullable<decimal> Longitude { get; set; }

    public Nullable<int> ward_Digits { get; set; }

}

}
